name = "vorseek-project"
type = "webpack"
account_id = "3e0eb5a25f1cd972f9c25271b1df1487"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2022-05-21"

[site]
bucket = "out"
entry-point = "./"
